<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alamat_perusahaan</name>
   <tag></tag>
   <elementGuidId>5ae18f96-659b-485c-acf2-68b0d04187a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_alamat_perusahaan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_alamat_perusahaan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f12a257-758b-4689-9d97-6a41803576f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d74afca4-c841-4b8b-a278-f4b9910449e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alamat_perusahaan</value>
      <webElementGuid>7776fbb9-a429-4b9c-a0a5-f7af6139e838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_alamat_perusahaan</value>
      <webElementGuid>bd2e8739-6ef3-4377-8bd4-7d23e1cc22b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_alamat_perusahaan&quot;)</value>
      <webElementGuid>76de8eb6-b8dd-408e-851a-f96a2c0422f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_alamat_perusahaan']</value>
      <webElementGuid>dad90627-8395-4a5d-8b01-54f96a4f72d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='id_form1']/table/tbody/tr[17]/td[3]/input</value>
      <webElementGuid>90ad5c59-b000-4fbd-a0a9-860714ece88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td[3]/input</value>
      <webElementGuid>47866405-b088-4368-83f7-be061111719a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'alamat_perusahaan' and @id = 'id_alamat_perusahaan']</value>
      <webElementGuid>dbecb17b-c64f-495d-bfa6-6d3cdb5c76b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
