<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bunga_isian</name>
   <tag></tag>
   <elementGuidId>c24108c7-04a3-4098-ba6b-9ee49f4dd7ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_bunga_isian</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_bunga_isian']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e22b262a-6be9-4a51-97b8-b58a103239b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b170c0b7-722d-48fd-a662-87d277c50a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bunga_isian</value>
      <webElementGuid>69c66e39-050c-4feb-b5fd-10d69208cfa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_bunga_isian</value>
      <webElementGuid>cccfc3a9-fc2a-4c2c-8024-1f9f7eecb17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>bunga isian</value>
      <webElementGuid>9aaca192-2bd1-401e-9fac-7a7d976840db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_bunga_isian&quot;)</value>
      <webElementGuid>e5c3e283-9678-4682-9951-16f5ec6aaf44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_bunga_isian']</value>
      <webElementGuid>224edeed-a06f-4916-a9b9-46239e256e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='id_form1']/table/tbody/tr[34]/td[3]/input</value>
      <webElementGuid>3656f72b-7946-486c-9f71-1a2948193548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[34]/td[3]/input</value>
      <webElementGuid>cffac48b-5c45-4eef-bffc-fa43e1bd2abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bunga_isian' and @id = 'id_bunga_isian' and @placeholder = 'bunga isian']</value>
      <webElementGuid>60c7e044-a9c0-4033-8baa-ff3c88d3586f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
