<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email_perusahaan_2</name>
   <tag></tag>
   <elementGuidId>9e5a2c51-f96e-4d84-a7da-de1b146d452e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_email_pic2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_email_pic2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83f90a48-bfba-4929-9dd7-6f7f2eb08f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>329742b8-9926-495e-94ad-6e53bb5160cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email_pic2</value>
      <webElementGuid>a2de2b47-60f7-46d8-88b7-66fe18a9383c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_email_pic2</value>
      <webElementGuid>48446407-5720-4af1-8da1-399d3508c56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_email_pic2&quot;)</value>
      <webElementGuid>3a6579b1-cc9e-44e7-95f3-3cc9dd466de7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_email_pic2']</value>
      <webElementGuid>24053454-214d-457e-9265-9d693bc79f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='id_form1']/table/tbody/tr[22]/td[3]/input</value>
      <webElementGuid>8a760ee6-0c78-4348-8c9f-56c304333050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[22]/td[3]/input</value>
      <webElementGuid>d9ae13b0-860d-4ddd-acee-0617658704fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'email_pic2' and @id = 'id_email_pic2']</value>
      <webElementGuid>35d9dc87-97fa-4b33-9a7f-2626efda680d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
