<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SU_su</name>
   <tag></tag>
   <elementGuidId>8b693960-5579-4d0a-aa52-e179d2edcb1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_su</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_su']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8caf0176-7776-4097-8332-598cbec496b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>259c4b02-429b-4c5b-8dc2-0b2648996ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>su</value>
      <webElementGuid>27afd75a-7b92-4e6b-8d0a-a24ba044980a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_su</value>
      <webElementGuid>c0a54511-c10b-4819-a45d-ee2664461a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_su&quot;)</value>
      <webElementGuid>74cfff28-d4b1-4586-9af6-599abe6e0eb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_su']</value>
      <webElementGuid>251f173c-b3bc-440b-b8d2-00acfd18018a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='id_form1']/table/tbody/tr[29]/td[3]/input</value>
      <webElementGuid>e98aa20c-e54b-4d90-8c2e-c511fef03152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[29]/td[3]/input</value>
      <webElementGuid>789250f0-5577-47cf-90a8-46beae363bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'su' and @id = 'id_su']</value>
      <webElementGuid>b241ae0f-224e-4526-a8d7-6a3b975a122e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
