<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pros_kenaikan_gaji</name>
   <tag></tag>
   <elementGuidId>899e826e-02b7-443a-8d56-0b5a36afee42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_pros_kenaikan_gaji</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_pros_kenaikan_gaji']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f6c23d7-8ca9-4a23-81b5-efb533bfea0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c46f0a8d-9d5f-41b1-947e-14db41f6a60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pros_kenaikan_gaji</value>
      <webElementGuid>31292803-7ffa-48f1-bb3c-b825f5150b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_pros_kenaikan_gaji</value>
      <webElementGuid>b5232eaa-24a1-437c-a947-387d280945f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_pros_kenaikan_gaji&quot;)</value>
      <webElementGuid>560120b1-9e17-4ba3-b087-7a59b578e5b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_pros_kenaikan_gaji']</value>
      <webElementGuid>40e10040-3246-483a-baa8-14434583dc24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='id_form1']/table/tbody/tr[33]/td[3]/input</value>
      <webElementGuid>53131143-9480-44a1-88a3-3fcfdf087b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[33]/td[3]/input</value>
      <webElementGuid>56971017-10c6-44e8-abf8-368bc8638b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'pros_kenaikan_gaji' and @id = 'id_pros_kenaikan_gaji']</value>
      <webElementGuid>0e17a018-031f-4f6e-af63-5553b83e6c6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
