<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EMAIL CBMCBE 2_email_cbe2</name>
   <tag></tag>
   <elementGuidId>95138bc7-abc1-4ba9-8b37-b8578bcb853f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_email_cbe2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_email_cbe2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>768d5ccb-6d30-4797-b2a5-f380a1bd01a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bf460f79-a781-4127-9e3b-edce7ac48f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email_cbe2</value>
      <webElementGuid>3ba17698-1938-4fd9-8b86-f570642cee11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_email_cbe2</value>
      <webElementGuid>21d1b800-c979-41fe-a7dc-32af829c2f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_email_cbe2&quot;)</value>
      <webElementGuid>f4138e9b-d3c0-4b0b-ab37-deff01af4e76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_email_cbe2']</value>
      <webElementGuid>ae872610-4db7-46ec-9964-66a1e0c1aed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='id_form1']/table/tbody/tr[26]/td[3]/input</value>
      <webElementGuid>8f1b441a-bdf8-47b8-bcf8-73dfd0bb4d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[26]/td[3]/input</value>
      <webElementGuid>badd8336-5617-4fcb-9f5f-0613c7fb82ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'email_cbe2' and @id = 'id_email_cbe2']</value>
      <webElementGuid>ad3a08a0-709d-4742-a8ca-def7f32fe696</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
