<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DESKRIPSI PRODUK_deskripsi_produk</name>
   <tag></tag>
   <elementGuidId>68ce7b52-df13-4dfc-a84e-7b9759bf3e60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_deskripsi_produk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_deskripsi_produk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7bec19af-bf56-4f5d-b9de-12ef845c3277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a5e2da75-00d6-4cf4-ba05-c3ea2ee68f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deskripsi_produk</value>
      <webElementGuid>f5413b25-21a7-4a74-bf42-d4a1a78b020f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_deskripsi_produk</value>
      <webElementGuid>20f1e4c8-13b7-4c96-adcd-859edb463300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_deskripsi_produk&quot;)</value>
      <webElementGuid>ca8414f2-e5db-4076-9099-357f7dca1399</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_deskripsi_produk']</value>
      <webElementGuid>40886bbc-1a70-4963-9b4a-f57563312377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='id_form1']/table/tbody/tr[40]/td[3]/input</value>
      <webElementGuid>22969d3a-4dc3-4061-86a5-ff6be579f09d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[40]/td[3]/input</value>
      <webElementGuid>069aa473-0df4-4693-8d0e-39db7aa8b509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'deskripsi_produk' and @id = 'id_deskripsi_produk']</value>
      <webElementGuid>829c7fb4-5a3b-4ea3-8067-d9a92eb65aca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
