<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TANGGAL PERTANGGUNGAN_tgl_mulai</name>
   <tag></tag>
   <elementGuidId>d55612c1-5f30-468d-9f28-e2da698f2d97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_tgl_mulai</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_tgl_mulai']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>390b5603-e6ca-4514-965e-93352f67260e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d0e5e362-41c6-44e7-850a-40162bcf4755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tgl_mulai</value>
      <webElementGuid>51233a41-f68f-43dc-b1d9-ddffa3e466e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_tgl_mulai</value>
      <webElementGuid>86c4edba-78f1-41d8-bf4b-c36468c21e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_tgl_mulai&quot;)</value>
      <webElementGuid>83d71c08-4007-4abb-a7da-ce6049c4f10e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_tgl_mulai']</value>
      <webElementGuid>526b0c93-b55d-4fcd-b051-a13f0bde3db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='id_form1']/table/tbody/tr[28]/td[3]/input</value>
      <webElementGuid>594b70fd-158f-4438-a35f-407927dacadd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[28]/td[3]/input</value>
      <webElementGuid>332f3a6c-5f36-4f5b-8133-3ba631712418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tgl_mulai' and @id = 'id_tgl_mulai']</value>
      <webElementGuid>0168fb9e-3e01-4b6d-aac8-00e2594e5ac4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
