<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EMAIL CBMCBE 1_email_cbe1</name>
   <tag></tag>
   <elementGuidId>4684ef55-93b0-4ee1-ad2b-f7e1814acceb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_email_cbe1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_email_cbe1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db26ee09-f1fa-4597-9053-a1f3d7a38e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b3ebeafa-5847-42be-a37a-25a5506e5cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email_cbe1</value>
      <webElementGuid>97eb32c7-bb64-444e-9756-0e8d644acb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_email_cbe1</value>
      <webElementGuid>f2b24a10-03eb-4dbf-9ed5-9a146f298788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_email_cbe1&quot;)</value>
      <webElementGuid>7366f998-b37b-4a1e-b89d-85bb8a38bf49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_email_cbe1']</value>
      <webElementGuid>90aac402-0d61-4bab-917c-3ebcfe42ee02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='id_form1']/table/tbody/tr[25]/td[3]/input</value>
      <webElementGuid>e3ab2d8b-23f2-480b-807a-d20708efc3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[25]/td[3]/input</value>
      <webElementGuid>389a3e71-419c-4fb6-9214-a0327cf0fa80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'email_cbe1' and @id = 'id_email_cbe1']</value>
      <webElementGuid>2eef557d-afbe-42db-997c-632ccf6ca501</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
