<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>keterangan_bunga</name>
   <tag></tag>
   <elementGuidId>bc314903-6dd8-4429-b63c-d71883bb2ca9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_keterangan_bunga_isian</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_keterangan_bunga_isian']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d102cbba-68bf-45a2-9a72-af0ae973b841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd1df99a-0532-4c3d-842a-cb567519882f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keterangan_bunga_isian</value>
      <webElementGuid>69576deb-00eb-4fc3-8b0c-2feac38654b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_keterangan_bunga_isian</value>
      <webElementGuid>b8cacdfc-a9f7-4e64-9c47-1654ebb00239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>keterangan bunga isian</value>
      <webElementGuid>de8f346a-42c2-4e47-871c-94e19127d0f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_keterangan_bunga_isian&quot;)</value>
      <webElementGuid>5a0f2caa-3e62-4c33-a83f-5088c5ab577c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_keterangan_bunga_isian']</value>
      <webElementGuid>ac82e091-0ef5-4dd3-8816-729a273b9b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='id_form1']/table/tbody/tr[34]/td[3]/input[2]</value>
      <webElementGuid>5fb4bb39-eda8-4355-90bc-33fc6a18b894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[34]/td[3]/input[2]</value>
      <webElementGuid>7b54de1c-5c69-4809-a397-2a5f180508bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'keterangan_bunga_isian' and @id = 'id_keterangan_bunga_isian' and @placeholder = 'keterangan bunga isian']</value>
      <webElementGuid>80a9ee8e-c8be-4b05-bff7-37a14a9f3351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
