<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nama_perwakilan_2</name>
   <tag></tag>
   <elementGuidId>1cea0edd-1aa6-4ba4-9fa5-0d96630dd55c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_cp2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_cp2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6731c162-dacd-45cd-8444-5492b4cba6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>805f9631-589a-4ced-9958-003382f2c4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cp2</value>
      <webElementGuid>10c5b169-0133-4c68-8080-3a03b321324d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_cp2</value>
      <webElementGuid>0145089b-3327-4697-a314-fe3bff9b65ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_cp2&quot;)</value>
      <webElementGuid>74a10acb-eff4-4f20-9cae-d6da9bf55d2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_cp2']</value>
      <webElementGuid>dc4552ac-2dbb-48f0-ae93-a798065d7675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='id_form1']/table/tbody/tr[20]/td[3]/input</value>
      <webElementGuid>4037b87c-554e-446e-aa0c-4a46308eddfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[20]/td[3]/input</value>
      <webElementGuid>363f3dc0-fbaf-4df1-ab3e-ab3ba1993b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cp2' and @id = 'id_cp2']</value>
      <webElementGuid>939418b4-b24e-4cc2-8705-48b53df52602</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
