<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nama_perwakilan_1</name>
   <tag></tag>
   <elementGuidId>5f2e2564-54c2-4048-b912-8b52bfe5ceed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_cp1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_cp1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03ba0d31-fa4d-4ac3-b7fa-cfcb281855ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>794fdda8-c2d4-4ee6-9e7f-55b58449b232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cp1</value>
      <webElementGuid>1dd48996-a793-4a3d-858e-b75beced65ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_cp1</value>
      <webElementGuid>cb38c5d0-06f3-45bb-a125-a79fdbb860e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_cp1&quot;)</value>
      <webElementGuid>9ed08bcf-1e7e-4995-b8a0-d2f7aade7368</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_cp1']</value>
      <webElementGuid>f6314015-72fb-4663-a871-6f97b7095e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='id_form1']/table/tbody/tr[19]/td[3]/input</value>
      <webElementGuid>9fdfdb07-dd11-4c25-862a-d83db045b4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td[3]/input</value>
      <webElementGuid>d12a2200-ddf2-4020-a959-055eaa4b3a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cp1' and @id = 'id_cp1']</value>
      <webElementGuid>ce2c3198-4305-4d33-8859-364ee9c2732d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
