<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>npwp_perusahaan</name>
   <tag></tag>
   <elementGuidId>6d181d8d-c5a6-48f4-847d-a124747b48a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_npwp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_npwp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f033f4f7-64a5-42a2-8589-eebae25623da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d72f92ab-a2e1-4c5b-921f-89756a47a98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>npwp</value>
      <webElementGuid>3215a7af-5bc7-4b4f-87bc-e90a5f5b7189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_npwp</value>
      <webElementGuid>cea2cfcd-987a-493e-9e9d-d02dc3c7b42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_npwp&quot;)</value>
      <webElementGuid>d784064b-66cc-4868-bb48-89cfd2557501</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_npwp']</value>
      <webElementGuid>44bdf642-0ce9-41ee-9a15-495d65e58d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='id_form1']/table/tbody/tr[18]/td[3]/input</value>
      <webElementGuid>361d970a-33fe-4dbd-aa14-7411154c745e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[18]/td[3]/input</value>
      <webElementGuid>543902e5-fb47-4da6-b575-eae3644d1a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'npwp' and @id = 'id_npwp']</value>
      <webElementGuid>5ebe6aa3-9f09-474e-bd3c-a7c4904d863e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
