<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pemegang_kontrak</name>
   <tag></tag>
   <elementGuidId>2d387dd1-8c01-466a-953f-3d5aed43efa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_pemegang_kontrak']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_pemegang_kontrak</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>437418f3-373b-4a5c-8029-41896a525036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b6918615-be5d-4db1-b903-dac638025663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pemegang_polis</value>
      <webElementGuid>df5a5d22-4de4-4a06-8105-4274d137ff8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_pemegang_kontrak</value>
      <webElementGuid>5867c6f0-1aaf-4759-b2ff-0a3661342884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_pemegang_kontrak&quot;)</value>
      <webElementGuid>09d730c9-2095-4735-8b60-081682b60910</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_pemegang_kontrak']</value>
      <webElementGuid>dc332bd3-4705-455a-9b29-0f8a6ea39bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='id_form1']/table/tbody/tr[15]/td[3]/input</value>
      <webElementGuid>faddd275-7557-420d-bf33-3e0424c251fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td[3]/input</value>
      <webElementGuid>1e948a06-9c9c-463b-a4d0-4d29604beb66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pemegang_polis' and @id = 'id_pemegang_kontrak']</value>
      <webElementGuid>739c1bf0-a6fa-4111-af76-1373e44ea6c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
